networks:
  net-auth:
    external: true
  

volumes:
  vol-db-auth:
    driver: local


services:
  app-auth:
    container_name: app-auth
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: fastapi dev src/app.py --host 0.0.0.0 --port 3000 --proxy-headers --reload
    env_file:
      - '.db.env'
    volumes:
      - ./src:/code/src
      - ./tests:/code/tests
      # - ./alembic:/code/alembic
    ports:
      - '3000:3000'
    networks:
      - net-auth
    depends_on:
      - db-auth

  db-auth:
    container_name: db-auth
    image: postgres:17-alpine
    # image: postgres:latest

    environment:
      POSTGRES_PASSWORD: postgres

    env_file:
      - '.db.env'

    volumes:
      - vol-db-auth:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    networks:
      - net-auth
